# Generated by Django 4.2 on 2023-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("item", models.CharField(max_length=50, verbose_name="Item")),
                ("alergian", models.CharField(max_length=50, verbose_name="Alergian")),
                ("price", models.CharField(max_length=50, verbose_name="Price")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu",
            },
        ),
        migrations.CreateModel(
            name="MenuGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "sub_title",
                    models.CharField(max_length=50, verbose_name="Sub_Title"),
                ),
                ("title_desc", models.TextField(verbose_name="Title_Desc")),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
        ),
    ]
